#app:
 #   resource: "@AppBundle/Controller/"
  #  type:     annotation

home:
    path:       /
    defaults:   { _controller: HomeBundle:Default:index }
    
formulario:
    path:       /{tipo}
    defaults:   { _controller: UserBundle:Formulario:index }