home:
    path:       /
    defaults:   { _controller: HomeBundle:Default:index }

inicio:
    path:       /inicio
    defaults:   { _controller: UserBundle:Inicio:index }

user:
    path:       /user
    defaults:   { _controller: UserBundle:Inicio:user}
           

admin:
    path:       /admin
    defaults:   { _controller: UserBundle:Inicio:admin }

root:
    path:       /root
    defaults:   { _controller: UserBundle:Inicio:root }

login:
    path:       /login
    defaults:   { _controller: UserBundle:Formulario:login }
    
registro:
    path:       /registro
    defaults:   { _controller: UserBundle:Formulario:registro }