home:
    path:       /
    defaults:   { _controller: HomeBundle:Default:index }

inicio:
    path:       /inicio
    defaults:   { _controller: UserBundle:Inicio:index }

admin:
    path:       /admin
    defaults:   { _controller: UserBundle:Inicio:index }

root:
    path:       /root
    defaults:   { _controller: UserBundle:Inicio:index }

login:
    path:       /login
    defaults:   { _controller: UserBundle:Formulario:login }
    
registro:
    path:       /registro
    defaults:   { _controller: UserBundle:Formulario:registro }